name: LaCoro
description: A new Flutter application.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:

  flutter_localizations:
    sdk: flutter

  flutter:
    sdk: flutter

  data:
    path: ./data

  domain:
    path: ./domain

  responsive_framework: ^0.0.7
  step_progress_indicator: ^0.2.2+5
  pull_to_refresh: ^1.4.5
  flutter_dotenv: ^2.1.0
  parse_server_sdk: ^1.0.26
  flutter_simple_dependency_injection: ^1.0.2+1
  flutter_bloc: ^4.0.0
  equatable: ^1.1.0
  google_fonts: ^1.0.0
  pin_code_fields: ^2.5.1
  scroll_to_index: ^1.0.6
  google_maps_flutter: ^0.5.27
  geolocator: ^5.3.1
  shared_preferences: ^0.5.7
  lazy_load_scrollview: ^1.1.0
  uuid: 2.0.4
  stepper_touch: ^0.0.1
  pubnub: ^1.1.3
  intl_phone_number_input: ^0.4.6+2

  firebase_core: ^0.5.0
  firebase_auth: ^0.18.0+1

  cupertino_icons: ^0.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^1.8.1
  flutter_launcher_icons: "^0.7.3"

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/icon.png"


# The following section is specific to Flutter.
flutter:

  uses-material-design: true

  assets:
    - assets/loading_resource.gif
    - assets/app_logo.png
    - development.env

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: AppIcons
      fonts:
        - asset: assets/AppIcons.ttf
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
